apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-main-headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ include "vault.fullname" . }}-main

  ports:
    - port: 8200
      name: http
    - port: 8201
      name: internal