global:
  namespace: "default"
  # replicacount: 5
  fullnameOverride: "webapp"

deployment:
  image:
    name: nginx
    tag: latest
    pullPolicy: IfNotPresent
  livenessProbe:
    httpGet:
      path: "/"
      port: http
  readinessProbe:
    httpGet:
      path: "/"
      port: http
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 500m
  affinity:
    enabled: true # Set to false to disable podAntiAffinity
    preferred:
      enabled: false
    required:
      enabled: true
    topologyKey: "topology.kubernetes.io/hostname" # distribution according to the Hosts
 
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPU: 80
    targetMemory: 80

  topologySpreadConstraints:
    enabled: true
    whenUnsatisfiable: "DoNotSchedule" # Options: "DoNotSchedule", "ScheduleAnyway"
    topologyKey: "topology.kubernetes.io/hostname"    # distribution according to the Hosts

  volumes:
    enabled: true
    configMaps:
      - name: index
        mountPath: /usr/share/nginx/html
        data:
          index.html: |
            Hello! Opstree
