name: kubelift-consumer
component: consumer

base:
  image:
    pullPolicy: "Always"
    repository: ""
    tag: latest
    pullSecrets: ""
  existingSecret: kubelift-consumer

replicaCount: 1

healthcheck:
  enabled: false
  statusPath: /health

service:
  type: ClusterIP
  port: 8080

resources: {}

volumes:
  configMaps:
    - name: kubelift-consumer-config
      mountPath: /etc/kubelift/
      data:
        config.yaml: |
          {}

livenessProbe: {}
readinessProbe: {}

ingress:
  enabled: false

internalIngress:
  enabled: false

autoscaling:
  enabled: false
