apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redis-operator-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ .Values.service.name }}.{{ .Values.service.namespace }}.svc
  - {{ .Values.service.name }}.{{ .Values.service.namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: redis-operator
  secretName: {{ .Values.certificate.secretName }}
