apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlagSource
metadata:
  name: flag-source
  namespace: {{ .Values.namespace }}
spec:
  sources:
    - source: {{ .Values.namespace }}/{{ include "flagd.name" . }}-flags
      provider: kubernetes
