apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flagds.core.openfeature.dev
spec:
  group: core.openfeature.dev
  scope: Namespaced
  names:
    plural: flagds
    singular: flagd
    kind: Flagd
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
