apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kafka.fullname" . }}-zookeeper-data
  namespace: kubelift
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.zookeeper.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.zookeeper.persistence.size }}
  storageClassName: {{ .Values.zookeeper.persistence.storageClass | quote }}
