apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-zookeeper
  namespace: kubelift
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
  selector:
    app.kubernetes.io/name: {{ include "kafka.name" . }}-zookeeper
    app.kubernetes.io/instance: {{ .Release.Name }}
