# Chart.yaml
apiVersion: v2
name: harbor-custom
description: My enterprise Harbor wrapper
type: application
version: 1.0.0
appVersion: "2.10.0"

dependencies:
  - name: harbor
    version: "1.15.0" # Current stable version of the chart
    repository: "https://helm.goharbor.io"
