apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
{{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  parentRefs:
{{- range .Values.parentRefs }}
  - name: {{ .name }}
    namespace: {{ .namespace }}
{{- end }}
  hostnames:
{{- range .Values.hostnames }}
  - {{ . | quote }}
{{- end }}
  rules:
{{- range .Values.rules }}
  - matches:
{{- range .matches }}
    - path:
        type: {{ .path.type }}
        value: {{ .path.value | quote }}
{{- end }}
    backendRefs:
{{- range .backendRefs }}
    - name: {{ .name }}
      kind: {{ .kind }}
      port: {{ .port }}
{{- end }}
{{- end }}
