apiVersion: v1
kind: Service
metadata:
# I would put labels here later - shubham
  name: {{ .Values.service.name }}
  # The namespace to be changed to release namespace - shubham
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
