apiVersion: v1
kind: Service
metadata:
# I would put labels here later - shubham
  name: {{ .Values.service.name }}
  namespace:  {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
