{{- if .Values.csiVolume.enabled }}
{{- range $index, $name := .Values.csiVolume.name }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $name }}-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ index $.Values.secretObject.arn $index }}
          objectVersionLabel: AWSCURRENT
          objectType: secretsmanager
          objectAlias: {{ index $.Values.secretObject.alias $index }}
---
{{- end }}
{{- end }}