#ConfigMap mounted as volumes
{{- if .Values.deployment.volumes.configMaps }}
{{- if .Values.deployment.volumes.enabled }}
{{ $header := .Values.deployment.volumes.configFileCommonHeader | default "" }}
{{ $root := . }}
{{ range $cm := .Values.deployment.volumes.configMaps}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" $root }}-{{ $cm.name }}-cm
  namespace: {{ $root.Values.global.namespace | quote }}
data:
  {{- if $cm.data }}
  {{- range $filename, $content := $cm.data }}
  # property-like keys; each key maps to a simple value
  {{ $filename }}: |-
{{ $content | toString | indent 4}}
  {{- end }}
  {{- end }}
  {{- if $cm.files }}
  {{- range $file := $cm.files }}
  {{ $file.destination }}: |
{{ $header | toString | indent 4 }}
    {{ $root.Files.Get "$file.source" }}
  {{- end}}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
