apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: alertmanager-
namespace: monitoring
commonLabels:
  app: kube-alertmanager
  release: kube
  prometheus: kube

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: kube-alertmanager
    files:
      - config/alertmanager.yaml
    type: Opaque
