{{- if .Values.volumes.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.common.name }}
  labels: 
    app.kubernetes.io/name: {{ .Values.volumes.common.name | default .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- include "global.labels" .Values.volumes.common | indent 4 }}
spec:
  {{- if or .Values.storageClass.name .Values.volumes.common.storageClassName }}
  storageClassName: {{ default .Values.storageClass.name .Values.volumes.common.storageClassName }}
  {{- end }}
  accessModes:
    {{- include "volume.volumeAccessModes" .Values.volumes.common | indent 4 }}
  resources: {{- include "volume.volumeResources" .Values.volumes.common | nindent 4 }}
{{- end }}
