apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kongclusterplugins.configuration.konghq.com
spec:
  group: configuration.konghq.com
  scope: Cluster
  names:
    plural: kongclusterplugins
    singular: kongclusterplugin
    kind: KongClusterPlugin
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
