{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flagd-operator.fullname" . }}-backup-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flagd-operator.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.backup.minio.accessKey | b64enc }}
  secretKey: {{ .Values.backup.minio.secretKey | b64enc }}
{{- end }}
