{{- if .Values.backup.enabled -}}
{{- if .Values.backup.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flagd-config-chart-dr.backupServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-backup-role
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
rules:
  - apiGroups: ["core.openfeature.dev"]
    resources: ["featureflags", "featureflagsources"]
    verbs: ["get", "list"]
  - apiGroups: ["flagd.dev"]
    resources: ["flagdconfigs"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-backup-rolebinding
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "flagd-config-chart-dr.fullname" . }}-backup-role
subjects:
  - kind: ServiceAccount
    name: {{ include "flagd-config-chart-dr.backupServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
