{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-backup-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.backup.minio.accessKey | b64enc }}
  secretKey: {{ .Values.backup.minio.secretKey | b64enc }}
  {{- if and .Values.restore.minio.accessKey (ne .Values.restore.minio.accessKey "") }}
  restoreAccessKey: {{ .Values.restore.minio.accessKey | b64enc }}
  restoreSecretKey: {{ .Values.restore.minio.secretKey | b64enc }}
  {{- end }}
{{- end }}
