apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: {{ .Values.flagdSourceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
spec:
  flagSpec:
    flags:
{{- range $flagName, $flag := .Values.flags }}
      {{ $flagName }}:
        state: {{ $flag.state }}
        variants:
          on: {{ index $flag.variants "on" }}
          off: {{ index $flag.variants "off" }}
        defaultVariant: "{{ $flag.defaultVariant }}"
{{- end }}
