apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlagSource
metadata:
  name: {{ .Values.flagdSourceName }}
  namespace: {{ .Release.Namespace }}
spec:
  sources:
    - source: {{ .Release.Namespace }}/{{ .Values.flagdSourceName }}
      provider: kubernetes
