apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-grpc
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.flagd.ingress.host }}
      secretName: {{ .Values.flagd.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.flagd.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.flagdSourceName }}
                port:
                  number: 8013
