{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.service.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: {{ .Values.metrics.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "flagd-config-chart-dr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
