---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-manager-role
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
rules:
  - apiGroups: ["core.openfeature.dev"]
    resources: ["flagds", "featureflags", "featureflagsources"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["core.openfeature.dev"]
    resources: ["flagds/status", "featureflags/status", "featureflagsources/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["core.openfeature.dev"]
    resources: ["flagds/finalizers", "featureflags/finalizers", "featureflagsources/finalizers"]
    verbs: ["update"]
  - apiGroups: ["flagd.dev"]
    resources: ["flagdconfigs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "services", "serviceaccounts", "pods"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-manager-rolebinding
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "flagd-config-chart-dr.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "flagd-config-chart-dr.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "flagd-config-chart-dr.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "flagd-config-chart-dr.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
