{{- if .Values.tls.enabled -}}
{{- $ca := genCA "flagd-operator-ca" 3650 -}}
{{- $cert := genSignedCert (include "flagd-operator.fullname" .) nil (list (printf "%s.%s.svc" (include "flagd-operator.fullname" .) .Release.Namespace) (printf "%s.%s.svc.cluster.local" (include "flagd-operator.fullname" .) .Release.Namespace)) 3650 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flagd-operator.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flagd-operator.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
