{{- if and .Values.ui.enabled (not .Values.ui.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-ui-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.ui.auth.username | b64enc }}
  password: {{ .Values.ui.auth.password | b64enc }}
  secretKey: {{ .Values.ui.auth.secretKey | b64enc }}
{{- end }}
