{{- if and .Values.ui.enabled (not .Values.ui.sso.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-ui-sso
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flagd-config-chart-dr.labels" . | nindent 4 }}
type: Opaque
data:
  clientId: {{ .Values.ui.sso.clientId | b64enc }}
  clientSecret: {{ .Values.ui.sso.clientSecret | b64enc }}
{{- end }}
