{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flagd-config-chart-dr.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flagd-config-chart-dr.uiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "flagd-config-chart-dr.uiSelectorLabels" . | nindent 4 }}
{{- end }}
