{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "keycloak.fullname" .) }}
  {{- with .Values.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ required "db.password is required when existingSecret is not set" .Values.db.password | quote }}
  admin-password: {{ required "auth.adminPassword is required when existingSecret is not set" .Values.auth.adminPassword | quote }}
{{- end }}
