apiVersion: v2
name: otel-operator
appVersion: "0.124.0"
description: A Helm chart for OpenTelemetry Operator
type: application
version: 1.0.0
maintainers:
  - name: ashwani-opstree
    email: ashwani.singh@opstree.com
  - name: Varunarora2201
    email: varun.kumar@opstree.com
dependencies:
  - name: opentelemetry-operator
    version: 0.102.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    alias: operator
    condition: operator.enabled