apiVersion: v2
appVersion: 0.149.0
dependencies:
- alias: operator
  condition: operator.enabled
  name: opentelemetry-operator
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts/
  tags:
  - operator
  version: 0.111.0
description: A Helm chart for Opentelemetry Operator
name: otel-operator
type: application
version: 1.0.1
maintainers:
  - name: ashwani-opstree
    email: ashwani.singh@opstree.com
  - name: Varunarora2201
    email: varun.kumar@opstree.com
