{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.name }}
  labels: 
    app.kubernetes.io/name: {{ .Values.mysql.service.name | default .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- include "global.labels" .Values.mysql | indent 4 }}
stringData:
  # MYSQL_DATABASE: {{ .Values.mysql.secret.database }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secret.password }}
{{- end }}