transit:
  enabled: true
  replicaCount: 2

main:
  enabled: true
  replicaCount: 6

image:
  repository: hashicorp/vault
  tag: "1.21.4"

vault:
  ui: true
  disable_mlock: true
  log_level: "info"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

nodeSelector: {}
tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: vault-main
          topologyKey: kubernetes.io/hostname

persistence:
  size: 5Gi
  storageClass: "standard" # Recommended: gp3, pd-ssd, etc. in real clusters

service:
  type: ClusterIP

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: vault.local
      paths:
        - path: /
          pathType: Prefix
  tls: []