{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccount.name }}
  labels:
    {{- include "spendsmart.labels" . | nindent 4 }}
  annotations:
    instrumentation.opentelemetry.io/inject-python: observability/otel-instrumentation
---
{{- end }}

{{- if .Values.engine.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.engine.serviceAccount.name }}
  labels:
    {{- include "spendsmart.labels" . | nindent 4 }}
  annotations:
    instrumentation.opentelemetry.io/inject-python: observability/otel-instrumentation
---
{{- end }}

{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccount.name }}
  labels:
    {{- include "spendsmart.labels" . | nindent 4 }}
  annotations:
    instrumentation.opentelemetry.io/inject-nodejs: observability/otel-instrumentation
---
{{- end }}

{{- if .Values.cloudsentry.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cloudsentry.serviceAccount.name }}
  labels:
    {{- include "spendsmart.labels" . | nindent 4 }}
{{- end }}
