apiVersion: v2
name: tempo-standalone
appVersion: "2"
description: A Helm chart for Tempo Standalone setup
type: application
version: 1.0.0
maintainers:
  - name: ashwani-opstree
    email: ashwani.singh@opstree.com
  - name: Varunarora2201
    email: varun.kumar@opstree.com
dependencies:
  - alias: tempo
    condition: tempo.enabled
    name: tempo
    repository: https://grafana.github.io/helm-charts
    version: 1.23.0