apiVersion: v2
name: opentelemetry-operator
description: A Helm chart for Opentelemetry Operator
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: tempo
    version: 1.10.1
    repository: https://grafana.github.io/helm-charts
    alias: tempo
    tags:
      - tempo
    condition: tempo.enabled