tempo:
  enabled: true
  fullnameOverride: tempo
  metricsPort: 3200

  tempo:
    repository: quay.io/opstree/tempo
    tag: "2.10.4-debian13"
    retention: 24h
    memBallastSizeMbs: 1024
    metricsGenerator:
      enabled: false

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000

  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  rbac:
    create: true

  service:
    type: ClusterIP

  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 150m
      memory: 150Mi

  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists

  persistence:
    enabled: true
    size: 10Gi

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  initContainers:
    - name: volume-permissions
      image: quay.io/opstree/busybox:1-alpine3.23
      command:
        - sh
        - -c
        - |
          chown -R 1000:1000 /var/tempo
      volumeMounts:
        - name: storage
          mountPath: /var/tempo
