{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-demo.fullname" . }}-nginx
  labels:
    {{- include "spring-demo.labels" . | nindent 4 }}
    {{- include "spring-demo.nginx.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "spring-demo.nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spring-demo.nginx.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "spring-demo.fullname" . }}-nginx-conf
{{- end }}
