name: sentryfuse-webhook
component: webhook

podAnnotations:
  instrumentation.opentelemetry.io/inject-go: observability/otel-instrumentation
  rems.owner/cto: sandeep
  rems.owner/dev: samyak
  rems.owner/devops: prashant
  rems.owner/manager: abhishek.dubey
  rems.owner/qa: shwetabh.vats
  rems.service/category: application
  rems.service/environment: prod
  rems.service/group: sentryfuse
  rems.service/layer: backend
  rems.service/name: sentryfuse-webhook
  rems.service/severity: critical
  rems.service/technology: golang

base:
  image:
    pullPolicy: "Always"
    repository: harbor.ldc.opstree.dev/coe/sentryfuse-webhook
    tag: latest
    pullSecrets: "reg-ldc-coe-regcred"
  existingSecret: sentryfuse-webhook

replicaCount: 1

healthcheck:
  enabled: false
  statusPath: /health

service:
  type: ClusterIP
  port: 8080

resources: {}

volumes:
  configMaps:
    - name: sentryfuse-webhook-config
      mountPath: /etc/sentryfuse/
      data:
        config.yaml: |
          kafka:
            brokers: ["192.168.10.52:9092"]


livenessProbe: {}
readinessProbe: {}

ingress:
  enabled: false

internalIngress:
  enabled: false

autoscaling:
  enabled: false
