postgresVersion: 16
pause: false
unmanaged: false
standby:
  enabled: false
instances:
- name: instance1
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi

proxy:
  pgBouncer:
    replicas: 2
    resources:
      limits:
        cpu: 200m
        memory: 128Mi