apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.publicapi.name }}
  labels: 
    app.kubernetes.io/name: {{ .Values.publicapi.name | default .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- include "global.labels" .Values.publicapi | indent 4 }}
spec:
  {{- if not .Values.publicapi.hpa.enabled }}
  replicas: {{ .Values.publicapi.replicas }}
  {{- end}}
  selector:
    matchLabels:
      {{- include "global.labels" .Values.publicapi | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "global.labels" .Values.publicapi | indent 8 }}
    spec:
      {{- if ne .Values.commonServiceAccount "" }}
      serviceAccountName: {{ .Values.commonServiceAccount }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.common.securityContext.runAsUser }}
        runAsGroup: {{ .Values.common.securityContext.runAsGroup }}
        fsGroup: {{ .Values.common.securityContext.fsGroup }}
        {{- if .Values.common.securityContext.fsGroupChangePolicy }}
        fsGroupChangePolicy: "{{- .Values.common.securityContext.fsGroupChangePolicy -}}"
        {{- end }}
        {{- if .Values.common.securityContext.supplementalGroups }}
        supplementalGroups:
          {{- range $supplementalGroup := .Values.common.securityContext.supplementalGroups }}
        - {{- $supplementalGroup -}}
          {{- end }}
        {{- end }}
      {{- include "workload.imagePullSecrets" .Values | nindent 6 }}
      containers:
        - tty: true
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: HOME_PATH_OF_HOST
            value: {{ .Values.envJson.homeDirectoryForSteps }}
          {{- if .Values.optimizedRun.withPermission }}
          - name: BP_PERMISSION
            value: "1"
          {{- end }}
          {{- if .Values.optimizedRun.firstTime }}
          - name: RECURSIVE_FILE_PERMISSION
            value: "1"
          {{- end }}
          image: "{{- .Values.imagePullSecrets.dockerConfig.registry -}}/{{- .Values.publicapi.image.name -}}:{{- .Values.publicapi.image.tag -}}"
          imagePullPolicy: {{ .Values.publicapi.imagePullPolicy }}
          name: {{  .Values.publicapi.name }}
          securityContext:
            allowPrivilegeEscalation: false
            # capabilities:
            #   drop:
            #   - ALL
          ports:
            {{- include "workload.ports" .Values.publicapi.service | indent 12 }}
          volumeMounts:
            {{- include "workload.volumeMounts" .Values.publicapi | indent 12 }}
          {{- include "workload.resources" .Values.publicapi | indent 10 }}
          {{- include "workload.startupProbe" .Values.publicapi | indent 10 }}
          {{- include "workload.livenessProbe" .Values.publicapi | indent 10 }}
          {{- include "workload.readinessProbe" .Values.publicapi | indent 10 }}
      {{- if .Values.publicapi.nodeSelector.enabled }}
      nodeSelector:
        {{- toYaml .Values.publicapi.nodeSelector.labels | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      volumes:
        {{- include "workload.volumes" .Values.publicapi | indent 8 }} 
