apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.publicapi.service.name }}
  labels: 
    app.kubernetes.io/name: {{ .Values.publicapi.service.name | default .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- include "global.labels" .Values.publicapi | indent 4 }}
spec:
  selector:
    {{- include "global.labels" .Values.publicapi | indent 4 }}
  type: {{ .Values.publicapi.service.type}}
  ports:
    {{- include "service.servicePorts" .Values.publicapi.service | indent 4 -}}
