apiVersion: v2
name: outline
description: Outline Wiki Helm Chart using external Postgres and Redis
type: application

version: 1.0.0
appVersion: "0.82.0"

keywords:
  - outline
  - wiki
  - knowledge-base
  - outlinewiki

maintainers:
  - name: platform-team

home: https://www.getoutline.com