---
apiVersion: v1
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
engine: gotpl
maintainers:
  - name: Opstree Solutions
name: redis-cluster
sources:
  - https://github.com/ot-container-kit/redis-operator
version: 0.9.0
appVersion: "0.9.0"
home: https://github.com/ot-container-kit/redis-operator
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
- redis-exporter
icon: https://github.com/OT-CONTAINER-KIT/redis-operator/raw/master/static/redis-operator-logo.svg
