apiVersion: v1
kind: Namespace
metadata:
  name: flagd
  labels:
    app: flagd
    environment: dev
---
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: flagd-flags
  namespace: flagd
  labels:
    app: flagd
    environment: dev
spec:
  flagSpec:
    flags:
      my-feature:
        state: ENABLED
        variants:
          on: true
          off: false
        defaultVariant: on
      new-ui:
        state: ENABLED
        variants:
          on: true
          off: false
        defaultVariant: off
      dark-mode:
        state: ENABLED
        variants:
          on: true
          off: false
        defaultVariant: off
---
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlagSource
metadata:
  name: flag-source
  namespace: flagd
  labels:
    app: flagd
    environment: dev
spec:
  sources:
    - source: /flagd-flags
      provider: kubernetes
  port: 8013
  managementPort: 8014
  evaluator: json
---
apiVersion: core.openfeature.dev/v1beta1
kind: Flagd
metadata:
  name: flagd
  namespace: flagd
  labels:
    app: flagd
    environment: dev
spec:
  replicas: 1
  serviceType: ClusterIP
  featureFlagSource: flag-source
