tempo:
  enabled: true
  fullnameOverride: tempo
  tempo:
    retention: 168h
    resources:
      requests:
        cpu:  1
        memory: 2Gi
      limits:
        cpu: 1
        memory: 2Gi

  persistence:
    enabled: true

  serviceMonitor:
    enabled: true