tempo:
  enabled: true
  fullnameOverride: tempo
  tempo:
    retention: 168h
    resources:
      requests:
        cpu:  1
        memory: 2Gi
      limits:
        cpu: 1
        memory: 2Gi
    metricsGenerator:
      enabled: true
      remoteWriteUrl: "http://kube-prometheus.monitoring:9090/api/v1/write"

  persistence:
    enabled: true

  serviceMonitor:
    enabled: true