apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
