apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: pgns
  labels:
    app: postgres-exporter
    app.kubernetes.io/instance: pg-db
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '9187'
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: http
    port: 9187
    targetPort: 9187
  selector:
    app.kubernetes.io/instance: pg-db