pg-operator:
  enabled: true
pg-db:
  enabled: true
  users:
    - name: rhino
      databases:
        - zoo
      options: "NOSUPERUSER"
      password:
        type: ASCII
      secretName: "rhino-credentials"
  instances:
  - name: instance1
    replicas: 2
    dataVolumeClaimSpec:
      # storageClassName: default
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  pmm:
    enabled: false
    image:
      repository: percona/pmm-client
      tag: 2.42.0
  #  imagePullPolicy: IfNotPresent
    secret: cluster1-pmm-secret
    serverHost: monitoring-service
  #  resources:
  #    requests:
  #      memory: 200M
  #      cpu: 500m
  proxy:
    pgBouncer:
      replicas: 2
      config:
        global:
          client_tls_sslmode: prefer
  patroni:
    # Some values of the Liveness/Readiness probes of the patroni container are calulated using syncPeriodSeconds by the following formulas:
    # - timeoutSeconds:   syncPeriodSeconds / 2;
    # - periodSeconds:    syncPeriodSeconds;
    # - failureThreshold: leaderLeaseDurationSeconds / syncPeriodSeconds.
    syncPeriodSeconds: 10
    leaderLeaseDurationSeconds: 30
    dynamicConfiguration:
      postgresql:
        parameters:
          max_parallel_workers: 2
          max_worker_processes: 2
          shared_buffers: 1GB
          work_mem: 2MB
        pg_hba:
        - host    all mytest 123.123.123.123/32 reject
    switchover:
      enabled: "true"
      targetInstance: ""
