pmm:

  image:
    repository: percona/pmm-server
    tag: "3"
    pullPolicy: IfNotPresent

  replicaCount: 1


service:

  type: ClusterIP

  port: 443

  targetPort: 8443


ingress:

  enabled: false

  className: nginx

  host: ""

  tls:

    enabled: false

    secretName: pmm-tls


persistence:

  enabled: true

  storageClass: ""

  size: 5Gi


externalClickHouse:

  enabled: true

  host: clickhouse.opstree.dev

  port: 9000

  username: pmm_user

  password: pmmadmin@321


resources:

  requests:

    cpu: 250m

    memory: 1Gi

  limits:

    cpu: 2

    memory: 4Gi


networkPolicy:

  enabled: true


serviceMonitor:

  enabled: true


tls:

  certManager:

    enabled: false

    issuerRef:

      kind: ClusterIssuer

      name: letsencrypt-prod


backup:

  enabled: false


nodeSelector: {}

tolerations: []

affinity: {}
