pmm:
  image:
    repository: percona/pmm-server
    tag: "3"
    pullPolicy: IfNotPresent

  replicaCount: 1

service:
  type: ClusterIP
  port: 443
  targetPort: 8443

ingress:
  enabled: false
  className: nginx
  host: ""
  tls:
    enabled: false
    secretName: pmm-tls

persistence:
  enabled: true
  storageClass: ""
  size: 25Gi   

externalClickHouse:
  enabled: true
  host: 192.168.8.24
  port: 9000
  username: pmm_user
  password: pmmadmin@321

resources:
  requests:
    cpu: 100m
    memory: 512Mi
    ephemeral-storage: 1Gi
  limits:
    cpu: 2
    memory: 4Gi
    ephemeral-storage: 5Gi

podSecurityContext:
  fsGroup: 0

permissionFix:
  enabled: true
  image: busybox:1.36
  runAsUser: 1000
  fsGroup: 0

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: true

tls:
  certManager:
    enabled: false
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-prod

backup:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
