{{- range .Values.ec2NodeClasses }}
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .name }}
spec:
  amiFamily: {{ .amiFamily | default "AL2" }}
  role: {{ .role }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{ $.Values.clusterName }}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{ $.Values.clusterName }}"
  amiSelectorTerms:
    - id: "{{ .amiSelector.arm }}"
    - id: "{{ .amiSelector.amd }}"
{{- if .amiSelector.gpu }}
    - id: "{{ .amiSelector.gpu }}"
{{- end }}
{{- end }}
