apiVersion: v2
name: ingress-management
description: A Helm chart to manage HTTPRoute resources
version: 0.1.0
appVersion: "1.0"
home: https://github.com/ot-container-kit/helm-charts
repository: https://ot-container-kit.github.io/helm-charts
maintainers:
  - name: Sharvari Khamkar
keywords:
  - ingress
  - kong
  - httpRoute
  - kubernetes
icon: https://raw.githubusercontent.com/OT-CONTAINER-KIT/helm-charts/main/static/helm-chart-logo.svg
sources:
  - https://github.com/ot-container-kit/helm-charts
