---

# charts/ingress-management/values.yaml

# -- Name of the HTTPRoute and backend service (typically the app name)
name: ""

# -- Kubernetes namespace where the ingress-traffic
# -- referenced resources will be created
namespace: ""

# -- Optional annotations to apply to the HTTPRoute resource
annotations: {}

# -- Reference to the Gateway (parentRefs)
parentRefs:
  - name: ""

# -- Hostnames to be matched in the HTTPRoute
hostnames: []

# -- Routing rules for HTTPRoute
path:
  - type: PathPrefix
    value: ""
backendRefs:
      - name: ""
        kind: Service
        port: 80

# -----------------------------------------------------
# Example values.yaml File
# -----------------------------------------------------
# name: open-webui
# namespace: default

# annotations:
#   konghq.com/protocols: https
#   konghq.com/https-redirect-status-code: "301"

# parentRefs:
#  - name: kong

# hostnames:
#  - bp-ai.opstree.dev

# paths:
#  - type: PathPrefix
#    value: /

# backendRefs:
#  - name: open-webui
#    kind: Service
#    port: 80
