name: open-webui
namespace: default
annotations:
  konghq.com/protocols: "https"
  konghq.com/https-redirect-status-code: "301"

parentRefs:
  - name: kong
    namespace: default

hostnames:
  - bp-ai.opstree.dev

rules:
  - matches:
      - path:
          type: PathPrefix
          value: /
    backendRefs:
      - name: open-webui
        kind: Service
        port: 80

