apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "pmm.fullname" . }}

data:

  CLICKHOUSE_HOST: "{{ .Values.externalClickHouse.host }}"

  CLICKHOUSE_PORT: "{{ .Values.externalClickHouse.port }}"
