apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "pmm.fullname" . }}
  labels:
{{ include "pmm.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.pmm.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "pmm.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "pmm.name" . }}

    spec:

      serviceAccountName: {{ include "pmm.fullname" . }}

      securityContext:
        fsGroup: 0

{{- with .Values.podSecurityContext }}
{{ toYaml . | nindent 6 }}
{{- end }}

      initContainers:

        - name: fix-pmm-permissions

          image: busybox:1.36

          command:

            - sh

            - -c

            - |

              chown -R 1000:0 /srv

              chmod -R g+rwX /srv


          securityContext:

            runAsUser: 0


          volumeMounts:

            - name: pmm-data

              mountPath: /srv



      containers:

        - name: pmm-server

          image: "{{ .Values.pmm.image.repository }}:{{ .Values.pmm.image.tag }}"

          imagePullPolicy: {{ .Values.pmm.image.pullPolicy }}


          ports:

            - name: https

              containerPort: 8443



          env:

{{- if .Values.externalClickHouse.enabled }}

            - name: PMM_DISABLE_BUILTIN_CLICKHOUSE

              value: "1"


            - name: PMM_CLICKHOUSE_HOST

              value: "{{ .Values.externalClickHouse.host }}"


            - name: PMM_CLICKHOUSE_PORT

              value: "{{ .Values.externalClickHouse.port }}"


            - name: PMM_CLICKHOUSE_USER

              valueFrom:

                secretKeyRef:

                  name: {{ include "pmm.fullname" . }}-secret

                  key: clickhouse_username


            - name: PMM_CLICKHOUSE_PASSWORD

              valueFrom:

                secretKeyRef:

                  name: {{ include "pmm.fullname" . }}-secret

                  key: clickhouse_password

{{- end }}


          volumeMounts:

            - name: pmm-data

              mountPath: /srv



          resources:

{{ toYaml .Values.resources | nindent 12 }}



          readinessProbe:

            tcpSocket:

              port: 8443

            initialDelaySeconds: 60

            periodSeconds: 10



          livenessProbe:

            tcpSocket:

              port: 8443

            initialDelaySeconds: 120

            periodSeconds: 20



      volumes:

        - name: pmm-data

          persistentVolumeClaim:

            claimName: {{ include "pmm.fullname" . }}



      nodeSelector:

{{ toYaml .Values.nodeSelector | nindent 8 }}



      tolerations:

{{ toYaml .Values.tolerations | nindent 8 }}



      affinity:

{{ toYaml .Values.affinity | nindent 8 }}
