apiVersion: v1
kind: Secret

metadata:
  name: {{ include "pmm.fullname" . }}-secret

type: Opaque

stringData:

  PMM_CLICKHOUSE_USERNAME: {{ .Values.externalClickHouse.username | quote }}

  PMM_CLICKHOUSE_PASSWORD: {{ .Values.externalClickHouse.password | quote }}
