apiVersion: v1
kind: Service

metadata:
  name: {{ include "pmm.fullname" . }}

  labels:
{{ include "pmm.labels" . | indent 4 }}

spec:

  type: {{ .Values.service.type }}

  selector:
    app: {{ include "pmm.name" . }}

  ports:

    - name: https

      port: {{ .Values.service.port }}

      targetPort: {{ .Values.service.targetPort }}
