apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clickhouse.fullname" . }}-data
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
