---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisSentinel
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: middleware
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  clusterSize: {{ .Values.redisSentinel.clusterSize }}
  # Sentinel Config 
  redisSentinelConfig:
    redisReplicationName: {{ .Values.redisSentinelConfig.redisReplicationName }}
    masterGroupName: {{ .Values.redisSentinelConfig.masterGroupName | default "myMaster" | quote }}
    redisPort:  {{ .Values.redisSentinelConfig.redisPort | default "6379" | quote }}
    quorum: {{ .Values.redisSentinelConfig.quorum | default "2" | quote }}
    parallelSyncs: {{ .Values.redisSentinelConfig.parallelSyncs | default "1" | quote }}
    failoverTimeout: {{ .Values.redisSentinelConfig.failoverTimeout | default "180000" | quote }}
    downAfterMilliseconds:  {{ .Values.redisSentinelConfig.downAfterMilliseconds | default "30000" | quote }}
    {{- if .Values.externalConfig.enabled }}
    additionalSentinelConfig: "{{ .Release.Name }}-ext-config"
    {{- end }}
  # Kubernetes Config 
  kubernetesConfig:
    image: "{{ .Values.redisSentinel.image }}:{{ .Values.redisSentinel.tag }}"
    imagePullPolicy: "{{ .Values.redisSentinel.imagePullPolicy }}"
    resources:
      {{- toYaml .Values.redisSentinel.resources | nindent 6 }}
    {{- with .Values.redisSentinel.redisSecret }}
    redisSecret:
      name: "{{ .secretName }}"
      key: "{{ .secretKey }}"
    {{- end }}
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .Values.priorityClassName }}
  priorityClassName: "{{ . }}"
  {{- end }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.securityContext }}
  securityContext:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.TLS }}
  TLS:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.sidecars }}
  sidecars:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccountName }}
  serviceAccountName: "{{ . }}"
  {{- end }}
