{{- if .Values.externalService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-external-service
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: middleware
  {{- with .Values.externalService.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.externalService.serviceType }}
  selector:
    app: {{ .Release.Name }}
    redis_setup_type: sentinel
    role: sentinle
  ports:
    - protocol: TCP
      port: {{ .Values.externalService.port }}
      targetPort: 26379
      name: client
{{- end }}
