apiVersion: v2
name: psmdb-operator-db
description: A Helm chart for Percona Operator and Percona Server for MongoDB
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: psmdb-operator
    version: 1.16.3
    repository: https://percona.github.io/percona-helm-charts/
    alias: psmdb-operator
    tags:
      - psmdb-operator
    condition: psmdb-operator.enabled
  - name: psmdb-db
    version: 1.16.3
    repository: https://percona.github.io/percona-helm-charts/
    alias: psmdb-db
    tags:
      - psmdb-db
    condition: psmdb-db.enabled