psmdb-operator:
  enabled: true
psmdb-db:
  enabled: true
  unsafeFlags:
    replsetSize: true
  replsets:
    rs0:
      name: rs0
      size: 3
  backup:
    enabled: true
    image:
      repository: percona/percona-backup-mongodb
      tag: 2.4.1
    # annotations:
    #   iam.amazonaws.com/role: role-arn
    # podSecurityContext: {}
    # containerSecurityContext: {}
    # resources:
    #   limits:
    #     cpu: "300m"
    #     memory: "0.5G"
    #   requests:
    #     cpu: "300m"
    #     memory: "0.5G"
    storages:
      # s3-us-west:
      #   type: s3
      #   s3:
      #     bucket: S3-BACKUP-BUCKET-NAME-HERE
      #     credentialsSecret: my-cluster-name-backup-s3
      #     serverSideEncryption:
      #       kmsKeyID: 1234abcd-12ab-34cd-56ef-1234567890ab
      #       sseAlgorithm: aws:kms
      #       sseCustomerAlgorithm: AES256
      #       sseCustomerKey: Y3VzdG9tZXIta2V5
      #     retryer:
      #       numMaxRetries: 3
      #       minRetryDelay: 30ms
      #       maxRetryDelay: 5m
      #     region: us-west-2
      #     prefix: ""
      #     uploadPartSize: 10485760
      #     maxUploadParts: 10000
      #     storageClass: STANDARD
      #     insecureSkipTLSVerify: false
      # minio:
      #   type: s3
      #   s3:
      #     bucket: MINIO-BACKUP-BUCKET-NAME-HERE
      #     region: us-east-1
      #     credentialsSecret: my-cluster-name-backup-minio
      #     endpointUrl: http://minio.psmdb.svc.cluster.local:9000/minio/
      #     prefix: ""
        # azure-blob:
        #   type: azure
        #   azure:
        #     container: percona-container
        #     prefix: backups
        #     endpointUrl: https://perconasa.blob.core.windows.net
        #     credentialsSecret: perconasasecret
