{{- if and (not .Values.postgres.enabled) (not .Values.postgres.external.existingSecret) .Values.postgres.external.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-external-secret
  # namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.external.password | urlquery }}@{{ .Values.postgres.external.host }}:{{ .Values.postgres.external.port }}/{{ .Values.postgres.database }}"
{{- end }}
