{{- if and (not .Values.redis.enabled) (not .Values.redis.external.existingSecret) .Values.redis.external.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-external-secret
  # namespace: {{ .Values.namespace }}
type: Opaque 
stringData:
  REDIS_PASSWORD: {{ .Values.redis.external.password | quote }}
{{- end }}
