apiVersion: v2
name: loki
description: A Helm chart for loki
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: loki-distributed
    version: 0.76.1
    repository: https://grafana.github.io/helm-charts
    alias: logging
    tags:
      - logging
