apiVersion: v2
name: loki
description: A Helm chart for loki
type: application
version: 1.0.1
appVersion: 1.0.0
dependencies:
  - name: loki-distributed
    version: 0.76.1
    repository: https://grafana.github.io/helm-charts
    alias: distributed
    tags:
      - logging
    condition: distributed.enabled
  - name: promtail
    version: 6.16.4
    repository: https://grafana.github.io/helm-charts
    alias: promtail
    tags:
      - logging
  - name: loki
    version: 6.7.3
    repository: https://grafana.github.io/helm-charts
    alias: standalone
    tags:
      - logging
    condition: standalone.enabled