{{- if and .Values.externalSecrets .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "keycloak.fullname" . }}-secretstore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ default "us-east-1" .Values.externalSecrets.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "keycloak.serviceAccountName" . }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "keycloak.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "keycloak.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: {{ include "keycloak.dbSecretName" . }}
    creationPolicy: Owner
  data:
    {{- if not .Values.database.host }}
    - secretKey: db-host
      remoteRef:
        key: {{ .Values.externalSecrets.awsSecretName }}
        property: {{ default "host" .Values.externalSecrets.propertyHost }}
    {{- end }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.awsSecretName }}
        property: {{ default "password" .Values.externalSecrets.propertyPassword }}
    - secretKey: admin-password
      remoteRef:
        key: {{ default .Values.externalSecrets.awsSecretName .Values.externalSecrets.adminPasswordSecretName }}
        property: {{ default "admin-password" .Values.externalSecrets.propertyAdminPassword }}
{{- end }}
