{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.adminSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.admin.username | quote }}
  admin-password: {{ .Values.admin.password | quote }}
{{- end }}
---
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.dbSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | quote }}
{{- end }}
