apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backstage.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .Values.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "backstage.fullname" . }}
                port:
                  number: {{ .Values.backstage.service.port }}
