{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}
  BACKEND_SECRET: {{ .Values.secrets.backendSecret | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.secrets.keycloakClientId | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.keycloakClientSecret | quote }}
  KEYCLOAK_METADATA_URL: {{ .Values.secrets.keycloakMetadataUrl | quote }}
{{- end }}
