base:
  image:
    pullPolicy: "Always"
    command: []
    repository: registry.ldc.opstree.dev/sentryfuse/gitguard-consumer
    tag: latest
    pullSecrets: "sentryfuse-harbor-secret"
  config:
    POSTGRES_ADDR: ""
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"

healthcheck:
  enabled: true
  statusPath: /api/v1/healthz

autoscaling:
  enabled: false
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 65
  minReplicas: 10
  maxReplicas: 50

service:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080

resources: {}

replicaCount: 1

volumes:
  configMaps:
    - name: gitguard-config
      mountPath: /etc/gitguard/
      data:
        config.yaml: |
          postgres:
            addr: ""
            user: "postgres"
            password: "password"
            dbname: "git_guard"

ingress:
  enabled: false
  class: nginx
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: global-sign-opstree-com-2024
    kubernetes.io/ingress.allow-http: "false"

internalIngress:
  enabled: false
  class: nginx-internal
  annotations:
    kubernetes.io/ingress.allow-http: "true"
