global:
  resolve_timeout: 5m
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 30m
  receiver: "null"
  group_by:
    - job
    - alertname
    - severity
  routes:
    - receiver: "null"
      match:
        alertname: Watchdog
    - receiver: "alerts-infra"
      group_wait: 10s
      continue: true
      match_re:
        severity: warning|high
        channel: slack
        team: devops
receivers:
  - name: "null"
  # - name: "email"
  #   email_configs:
  #     - to: ''
  #       from: ''
  #       smarthost: ''
  #       auth_username: ''
  #       auth_password: ''
  #       require_tls: yes
  #       send_resolved: true
  - name: "alerts-infra"
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/'
        send_resolved: true
        channel: '#alerts-infra'
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.description }} - `{{ .Labels.severity }}`

          *Description:* {{ .Annotations.description }}

          *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}