apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-nginx
spec:
  replicas: 1
  selector:
    matchLabels: {component: nginx}
  template:
    metadata:
      labels: {component: nginx}
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      containers:
      - name: nginx
        image: {{ .Values.images.nginx }}
        ports:
        - containerPort: 8080
        env:
        - name: NGINX_ENTRYPOINT_QUIET_LOGS
          value: "1"
        volumeMounts:
        - name: nginx-tmp
          mountPath: /var/run
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-confd
          mountPath: /etc/nginx/conf.d
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-body
          mountPath: /etc/nginx/client_body_temp
        - name: nginx-proxy
          mountPath: /etc/nginx/proxy_temp
        - name: nginx-fastcgi
          mountPath: /etc/nginx/fastcgi_temp
        - name: nginx-scgi
          mountPath: /etc/nginx/scgi_temp
        - name: nginx-uwsgi
          mountPath: /etc/nginx/uwsgi_temp
      volumes:
      - name: nginx-tmp
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-confd
        emptyDir: {}
      - name: config
        configMap:
          name: harbor-nginx-config
      - name: nginx-body
        emptyDir: {}
      - name: nginx-proxy
        emptyDir: {}
      - name: nginx-fastcgi
        emptyDir: {}
      - name: nginx-scgi
        emptyDir: {}
      - name: nginx-uwsgi
        emptyDir: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-portal
spec:
  replicas: 1
  selector:
    matchLabels: {component: portal}
  template:
    metadata:
      labels: {component: portal}
    spec:
      securityContext:
        fsGroup: 10000
      containers:
      - name: portal
        image: {{ .Values.images.portal }}
        volumeMounts:
        - name: portal-tmp
          mountPath: /var/run
      volumes:
      - name: portal-tmp
        emptyDir: {}
