apiVersion: v1
kind: Service
metadata:
  name: harbor-core
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    component: core
---
apiVersion: v1
kind: Service
metadata:
  name: harbor-jobservice
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    component: jobservice

---
apiVersion: v1
kind: Service
metadata:
  name: harbor-portal
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    component: portal

---
apiVersion: v1
kind: Service
metadata:
  name: harbor-registry
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    component: registry

---
apiVersion: v1
kind: Service
metadata:
  name: harbor-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
  selector:
    component: nginx
