app:
  enabled: false

kube:
  enabled: true
  grafana:
    enabled: true
    sidecar:
      datasources:
        defaultDatasourceEnabled: false

pushgateway:
  enabled: false

blackbox:
  enabled: false

adapter:
    enabled: true