{{- if not .Values.litellm.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-litellm-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  masterKey: {{ .Values.litellm.masterKey | quote }}
  saltKey: {{ .Values.litellm.saltKey | quote }}
  {{- if .Values.litellm.providers.geminiApiKey }}
  geminiApiKey: {{ .Values.litellm.providers.geminiApiKey | quote }}
  {{- end }}
  {{- if .Values.litellm.providers.openaiApiKey }}
  openaiApiKey: {{ .Values.litellm.providers.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.litellm.providers.anthropicApiKey }}
  anthropicApiKey: {{ .Values.litellm.providers.anthropicApiKey | quote }}
  {{- end }}
{{- end }}
