{{- if .Values.litellm.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-litellm
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  minAvailable: {{ .Values.litellm.pdb.minAvailable }}
  selector:
    matchLabels:
      app: litellm
{{- end }}
