{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  # namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
{{- end }}
