{{- if and (not .Values.postgres.enabled) (not .Values.postgres.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-external-secret
  # namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.postgres.external.databaseUrl | quote }}
{{- end }}