{{- if and (not .Values.redis.enabled) (not .Values.redis.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-external-secret
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.external.password | quote }}
{{- end }}