{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}

          args:
            - "redis-server"
            - "--save"
            - "60"
            - "1"
            - "--maxmemory"
            - "{{ .Values.redis.maxmemory }}"
            - "--maxmemory-policy"
            - "allkeys-lru"

          ports:
            - containerPort: 6379

          volumeMounts:
            - name: data
              mountPath: /data

      volumes:
        - name: data
          emptyDir: {}
{{- end }}
