{{- if and .Values.sso.enabled (not .Values.sso.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sso-secret
  # namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GENERIC_CLIENT_ID: {{ .Values.sso.clientId | quote }}
  GENERIC_CLIENT_SECRET: {{ .Values.sso.clientSecret | quote }}
{{- end }}
