{{- if and .Values.sso.enabled (ne (toString .Values.sso.enabled) "false") (not .Values.sso.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sso-secret
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  GENERIC_CLIENT_ID: {{ .Values.sso.clientId | quote }}
  GENERIC_CLIENT_SECRET: {{ .Values.sso.clientSecret | quote }}
{{- end }}
