apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-initdb
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
    kubelift-init.sql: |
     DO
     $$
     BEGIN
       IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'kubelift') THEN
         CREATE ROLE kubelift LOGIN PASSWORD 'kubelift';
       END IF;
     END
     $$;

     DO
     $$
     BEGIN
       IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'kubelift') THEN
         CREATE DATABASE kubelift OWNER kubelift;
       END IF;
     END
     $$;
