apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.password | b64enc | quote }}
