apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-alertmanager-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app: kube-grafana
    prometheus: kube
data:
  kube-alertmanager.yaml: |-
    apiVersion: 1
    datasources:
      - name: "kube-alertmanager"
        type: alertmanager
        uid: alertmanager
        url: http://kube-alertmanager.monitoring:9093/
        access: proxy
        jsonData:
          handleGrafanaManagedAlerts: false
          implementation: prometheus
