apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app: kube-grafana
    prometheus: kube
data:
  tempo.yaml: |-
    apiVersion: 1
    datasources:
      - name: "tempo"
        type: tempo
        uid: tempo
        url: http://tempo.observability.svc.cluster.local:3100/
        access: proxy
        jsonData:
          handleGrafanaManagedAlerts: false
          implementation: prometheus
          nodeGraph:
            enabled: true
          search:
            hide: false
          lokiSearch:
            datasourceUid: loki
          tracesToLogs:
            datasourceUid: loki
            filterBySpanID: false
            filterByTraceID: true
            mapTagNamesEnabled: false
            tags:
              - app
