{{- if .Values.volumes }}
{{- if .Values.volumes.configMaps }}
{{ range $cm := .Values.volumes.configMaps}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cm.name }}
  labels:
    {{- include "base.labels" $ | nindent 4 }}
data:
  {{- range $filename, $content := $cm.data }}
  {{ $filename }}: |-
{{ $content | toString | indent 4}}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
