---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  {{- with .Values.replicaCount }}
  replicas: {{ . }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.base.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.base.image.pullSecrets }}
      {{- end }}
      serviceAccountName: {{ include "base.serviceAccountName" . }}
      terminationGracePeriodSeconds: 120
      containers:
        - name: {{ include "base.fullname" . }}
          image: "{{ .Values.base.image.repository }}:{{ .Values.base.image.tag }}"
          imagePullPolicy: {{ .Values.base.image.pullPolicy }}
          {{- if .Values.base.image.command }}
          command:
            {{- toYaml .Values.base.image.command | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.statusPath }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.statusPath }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
            failureThreshold: 3
          {{- if or .Values.base.config .Values.base.secret }}
          envFrom:
            {{- if .Values.base.config }}
            - configMapRef:
                name: {{ include "base.fullname" . }}
            {{- end }}
            {{- if .Values.base.secret }}
            - secretRef:
                name: {{ include "base.fullname" . }}
            {{- end }}
          {{- end }}
          {{- if .Values.volumes }}
          volumeMounts:
            {{- if .Values.volumes.configMaps }}
            {{- range $conf := .Values.volumes.configMaps }}
            - mountPath: {{ $conf.mountPath }}
              name: {{ $conf.name }}-volume
            {{- end }}
            {{- end }}
          {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- if .Values.volumes.configMaps }}
        {{- range $conf := .Values.volumes.configMaps }}
        - name: {{ $conf.name }}-volume
          configMap:
            name: {{ $conf.name }}
        {{- end }}
        {{- end }}
      {{- end }}
