---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.fullname" . }}
  annotations:
  {{- if .Values.service.metrics }}
    prometheus.io/path: "{{ .Values.service.metrics.path }}"
    prometheus.io/port: "{{ .Values.service.metrics.port }}"
    prometheus.io/scrape: "true"
  {{- end }}
  labels:
      {{- include "base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
