name: kubelift-frontend
component: frontend

base:
  image:
    pullPolicy: "Always"
    repository: ""
    tag: latest
    pullSecrets: ""
  existingSecret: kubelift-frontend

replicaCount: 1

healthcheck:
  enabled: false
  statusPath: /health

service:
  type: ClusterIP
  port: 80

resources: {}

volumes:
  configMaps:
    - name: kubelift-frontend-config
      mountPath: /etc/kubelift/
      data:
        config.yaml: |
          {}

livenessProbe: {}
readinessProbe: {}

ingress:
  enabled: false

internalIngress:
  enabled: false

autoscaling:
  enabled: false
