apiVersion: v2
name: pg-operator
description: 'A Helm chart to deploy the Percona Operator for PostgreSQL'
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: pg-operator
    version: ~1
    repository: https://percona.github.io/percona-helm-charts/
    alias: pg-operator
    tags:
      - pg-operator
    condition: pg-operator.enabled