image:
  repository: quay.io/opstree/fluent-bit
  tag: 5.0.3
testFramework:
  enabled: false
# securityContext:
#   runAsUser: 0
securityContext:
  runAsUser: 65532
  runAsGroup: 65532
  runAsNonRoot: true
  fsGroup: 65532
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
rbac:
  create: true
metricsPort: 2020
service:
  type: ClusterIP
resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 150m
    memory: 150Mi
tolerations:
- effect: NoExecute
  operator: Exists
- effect: NoSchedule
  operator: Exists
