{{- if not .Values.outline.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-outline-secret
type: Opaque
stringData:
  secretKey: {{ .Values.outline.secretKey | quote }}
  utilsSecret: {{ .Values.outline.utilsSecret | quote }}
  {{- if .Values.azure.enabled }}
  azureClientId: {{ .Values.azure.clientId | quote }}
  azureClientSecret: {{ .Values.azure.clientSecret | quote }}
  {{- end }}
{{- end }}