{{- if and .Values.backup.enabled (not .Values.backup.minio.existingSecret) }}
{{- $accessKey := .Values.backup.minio.accessKey }}
{{- $secretKey := .Values.backup.minio.secretKey }}
{{- if or (eq $accessKey "") (eq $secretKey "") }}
{{- fail "backup.minio.accessKey and backup.minio.secretKey must both be set in values.yaml when backup.minio.existingSecret is not provided" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-outline-backup-secret
  labels:
    app: outline
    component: backup
type: Opaque
data:
  {{ .Values.backup.minio.accessKeyKey }}: {{ $accessKey | b64enc }}
  {{ .Values.backup.minio.secretKeyKey }}: {{ $secretKey | b64enc }}
{{- end }}