kong:
  image: kong/kong-gateway:latest
  replicaCount: 2

  plugins:
    enabled: true
    list:
      - key-auth
      - jwt
      - rate-limiting
      - prometheus
      - opentelemetry
      - request-transformer   
      - acl

# -------------------------
# POSTGRES CONFIG
# -------------------------
externalPostgres:
  enabled: true
  host: 192.168.8.39
  port: 5432

postgresql:
  enabled: false

  auth:
    username: kong
    password: kongpass
    database: kong

# -------------------------
# SCALING
# -------------------------
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpu: 70

# -------------------------
# OBSERVABILITY
# -------------------------
observability:
  otel:
    endpoint: http://otel-collector:4318

monitoring:
  serviceMonitor:
    enabled: true

# -------------------------
# PLUGINS (ENABLE FLAGS)
# -------------------------
plugins:
  keyAuth: true
  jwt: true
  rateLimit: true
  prometheus: true
  opentelemetry: true

tls:
  enabled: false

installCRDs: true
