apiVersion: v2
name: kong-api-gateway
description: Enterprise Kong API Gateway Helm Chart (OT-style custom wrapper)
type: application
version: 1.0.0
appVersion: "3.9.0"

kong:
  image: kong/kong-gateway:3.9.0

postgres:
  host: postgres-postgresql
  user: kong
  password: kongpass
  database: kong

ingress:
  enabled: true
  className: nginx

tls:
  enabled: false
