config:
  APP_ENV: production
  LOG_LEVEL: info
  CONFIG_VERSION: "1.0.0"
  name: myapp-config
  env: production


hpa:
  name: myapp-hpa
  minReplicas: 1
  maxReplicas: 3
  enabled: false
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60


serviceAccount:
  name: my-service-account
  

secret:
  enabled: true
  name: myapp-secret
  FOO_SECRET: BAR
  
deployment: 
  name: my-deployment



image:
  enabled: false
  pullSecrets: ""
  name: my-container
  repository: myregistry/myapp
  tag: "1.0.0"
  pullPolicy: IfNotPresent
  command: []

healthcheck:
  statusPath: /health


volume:
  name: myapp-volume
  enabled: true

volumeMounts:
  name: myapp-volume-mount
  mountPath: /data
