apiVersion: v2
name: clickhouse
version: 0.1.0
description: A generic Helm chart for ClickHouse
appVersion: "23.12"
namespace: kubelift
icon: https://upload.wikimedia.org/wikipedia/commons/6/6a/ClickHouse_logo.png
keywords:
  - clickhouse
  - database
home: https://clickhouse.com/
sources:
  - https://github.com/ClickHouse/ClickHouse
maintainers:
  - name: Samyak Jain
    email: samyak.jain@opstree.com
    url: https://github.com/samyakjain1908

