replicaCount: 1

image:
  repository: 552171489163.dkr.ecr.ap-south-1.amazonaws.com/kubelift/clickhouse
  tag: "1-2026-04-25-012909"
  pullPolicy: IfNotPresent
  pullSecrets: sr-stage-aws-ecr-regcred

resources:
  requests:
    memory: "4Gi"
    cpu: "2"
  limits:
    memory: "8Gi"
    cpu: "4"

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 20Gi
  storageClass: ""

clickhouse:
  defaultUser: clickhouse
  defaultPassword: clickhouse
  appDb: kubelift
  appUser: kubelift
  appPassword: kubelift
