---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name | default "bp-regcred" }}
  # namespace: bp
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        {{ .Values.imagePullSecrets.dockerConfig.registry | quote }}: {
          "username": {{ .Values.imagePullSecrets.dockerConfig.username | quote }},
          "password": {{ .Values.imagePullSecrets.dockerConfig.password | quote }},
          {{- if .Values.imagePullSecrets.dockerConfig.email }}
          "email": {{ .Values.imagePullSecrets.dockerConfig.email | quote }},
          {{- end }}
          "auth": {{ printf "%s:%s" .Values.imagePullSecrets.dockerConfig.username .Values.imagePullSecrets.dockerConfig.password | b64enc | quote }}
        }
      }
    }
