vm:
  enabled: true


  ## VM Operator ##

  victoria-metrics-operator:
    enabled: true

    image:
      registry: quay.io
      repository: opstree/victoriametrics-operator
      tag: "v0.69.0"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 300Mi

    crds:
      # plain: true
      cleanup:
        enabled: false

    tolerations:
      - key: team
        operator: Equal
        value: "o11y"
        effect: NoSchedule
    nodeSelector:
      team: o11y

    serviceMonitor:
      enabled: true

    operator:
      disable_prometheus_converter: false

    env:
      # opstree hardened images — identified and pushed
      - name: VM_VMSINGLEDEFAULT_IMAGE
        value: "opstree/victoriamertics-victoriametrics"
      - name: VM_VMSINGLEDEFAULT_VERSION
        value: "v1.41.0"
      - name: VM_VMSINGLEDEFAULT_VERSION
        value: "v1.41.0"
      - name: VM_VMAGENTDEFAULT_IMAGE
        value: "opstree/victoriametrics-vmagent"
      - name: VM_VMAGENTDEFAULT_VERSION
        value: "v1.141.0"
      - name: VM_VMALERTDEFAULT_IMAGE
        value: "opstree/victoriametrics-vmalert"
      - name: VM_VMALERTDEFAULT_VERSION
        value: "v1.141.0"
      - name: VM_VMALERTMANAGER_ALERTMANAGERDEFAULTBASEIMAGE
        value: "opstree/alertmanager"
      - name: VM_VMALERTMANAGER_ALERTMANAGERVERSION
        value: "v0.32.0"
      - name: VM_CONFIG_RELOADER_IMAGE
        value: "opstree/victoriametrics-operator:config-reloader-v0.69.0"

      # upstream images — not yet hardened this can be hardenend
      - name: VM_VLOGSDEFAULT_IMAGE
        value: "victoriametrics/victoria-logs"
      - name: VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_IMAGE
        value: "victoriametrics/vmselect"
      - name: VM_VMCLUSTERDEFAULT_VMSTORAGEDEFAULT_IMAGE
        value: "victoriametrics/vmstorage"
      - name: VM_VMCLUSTERDEFAULT_VMINSERTDEFAULT_IMAGE
        value: "victoriametrics/vminsert"
      - name: VM_VMBACKUP_IMAGE
        value: "victoriametrics/vmbackupmanager"
      - name: VM_VMAUTHDEFAULT_IMAGE
        value: "victoriametrics/vmauth"

      # VictoriaMetrics Operator configuration
      - name: "VM_USECUSTOMCONFIGRELOADER"
        value: "true"
      - name: "VM_CONFIG_RELOADER_REQUEST_CPU"
        value: "unlimited"
      - name: "VM_CONFIG_RELOADER_REQUEST_MEMORY"
        value: "unlimited"
      - name: "VM_CONFIG_RELOADER_LIMIT_CPU"
        value: "unlimited"
      - name: "VM_CONFIG_RELOADER_LIMIT_MEMORY"
        value: "unlimited"
      - name: "VM_VMAGENTDEFAULT_USEDEFAULTRESOURCES"
        value: "false"
      - name: "VM_VMALERTMANAGER_USEDEFAULTRESOURCES"
        value: "false"
      - name: VM_CONTAINERREGISTRY
        value: "quay.io"

  ## Grafana — managed via standalone grafana chart

  grafana:
    enabled: true
    image:
      registry: quay.io
      repository: opstree/grafana
      tag: "12.4.3"
    grafana.ini:
      users:
        viewers_can_edit: true
      feature_toggles:
      provisioning: "true"
      kubernetesDashboards: "true"
    useStatefulSet: true
    serviceAccount:
      create: true
    adminUser: admin
    adminPassword: opstree@2014
    initChownData:
      enabled: true
    # securityContext:
    #   runAsUser: 472
    #   runAsGroup: 0
    #   fsGroup: 472
    #   runAsNonRoot: false
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
      fsGroup: 65532
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        drop:
            - ALL
      seccompProfile:
        type: RuntimeDefault
    testFramework:
      enabled: false
    sidecar:
      dashboards:
        enabled: true
      datasources:
        enabled: true
        defaultDatasourceEnabled: false
        label: grafana_datasource
        labelValue: "1"
    tolerations:
      - key: team
        operator: Equal
        value: "o11y"
        effect: NoSchedule
    nodeSelector:
      team: o11y
    serviceMonitor:
      enabled: false
    persistence:
      enabled: true
      type: sts
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      finalizers:
        - kubernetes.io/pvc-protection
  ## Alertmanager — managed via VMAlertManager CRD
  alertmanager:
    enabled: true
    spec:
      replicaCount: 1
      resources:
        limits:
          cpu: 250m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 500Mi
      tolerations:
        - key: team
          operator: Equal
          value: "o11y"
          effect: NoSchedule
      nodeSelector:
        team: o11y

  ## VMSingle ##

  vmsingle:
    enabled: true
    spec:
      retentionPeriod: "7d"
      extraArgs:
        dedup.minScrapeInterval: 60s
        search.maxUniqueTimeseries: "10000000000000"
        search.cacheTimestampOffset: 60m
        search.maxLabelsAPISeries: "10000000000000"
        search.maxMemoryPerQuery: 1GB
        search.maxPointsPerTimeseries: "10000000000000"
        search.maxQueryDuration: 10m
        search.maxQueryLen: "10000000000000"
        search.maxSeries: "10000000000000"
        maxLabelsPerTimeseries: "200"
        memory.allowedPercent: "75"
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "1"
          memory: 1Gi
      storage:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      tolerations:
        - key: team
          operator: Equal
          value: "o11y"
          effect: NoSchedule
      nodeSelector:
        team: o11y

  # Add this section to fix permissions
    initContainers:
      - name: volume-permissions
        image: quay.io/opstree/busybox:1-alpine3.23
        command:
          - sh
          - -c
          - |
            chown -R 1000:1000 /storage
        volumeMounts:
          - name: data
            mountPath: /storage

  ## VMAgent ##
  vmagent:
    enabled: true
    spec:
      scrapeInterval: 30s
      extraArgs:
        promscrape.maxScrapeSize: 200MB
        promscrape.streamParse: "true"
        promscrape.dropOriginalLabels: "true"
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 500Mi
      tolerations:
        - key: team
          operator: Equal
          value: "o11y"
          effect: NoSchedule
      nodeSelector:
        team: o11y

  ## VMAlert ##
  vmalert:
    enabled: true
    spec:
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 500Mi
      tolerations:
        - key: team
          operator: Equal
          value: "o11y"
          effect: NoSchedule
      nodeSelector:
        team: o11y

  ## Kube State Metrics ##
  kube-state-metrics:
    image:
      registry: "quay.io"
      repository: opstree/kube-state-metrics
      tag: "2.18.0-debian13"
      digest: "sha256:53525d253793ccb33f525781831df4d66f25634b90318f07b5c41ae1e5bb587b"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    tolerations:
      - key: team
        operator: Equal
        value: "o11y"
        effect: NoSchedule
    nodeSelector:
      team: o11y
  ## Node Exporter ##

  prometheus-node-exporter:
    image:
      registry: quay.io
      repository: opstree/node-exporter
      tag: "1.11.1-alpine3.23"
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi

  ## Disabled by default ##
  defaultDashboards:
    enabled: false

  defaultRules:
    create: false

  vmcluster:
    enabled: false

## Prometheus Operator CRDs — enabled, VM operator handles CRDs ##
prometheus-operator-crds:
  enabled: true
