{{- if .Values.main.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-main-config
  namespace: {{ .Release.Namespace }}
data:
  vault.hcl: |
    ui = {{ .Values.vault.ui | default true }}
    disable_mlock = {{ .Values.vault.disable_mlock | default true }}
    log_level = "{{ .Values.vault.log_level | default "info" }}"

    storage "raft" {
      path    = "/vault/data"
      node_id = "__NODE_ID__"

      {{- range $i := until (int .Values.main.replicaCount) }}
      retry_join {
        leader_api_addr = "http://{{ include "vault.fullname" $ }}-main-{{ $i }}.{{ include "vault.fullname" $ }}-main-headless.{{ $.Release.Namespace }}.svc.cluster.local:8200"
      }
      {{- end }}
    }

    seal "transit" {
      address    = "http://{{ include "vault.fullname" . }}-transit:8200"
      token      = "__TRANSIT_TOKEN__"
      key_name   = "unseal-key"
      mount_path = "transit/"
    }

    api_addr     = "http://__NODE_ID__.{{ include "vault.fullname" . }}-main-headless.{{ .Release.Namespace }}.svc.cluster.local:8200"
    cluster_addr = "http://__NODE_ID__.{{ include "vault.fullname" . }}-main-headless.{{ .Release.Namespace }}.svc.cluster.local:8201"

    listener "tcp" {
      address         = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable     = 1
    }
{{- end }}
