{{- if .Values.transit.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-transit-config
  namespace: {{ .Release.Namespace }}
data:
  vault.hcl: |
    ui = {{ .Values.vault.ui | default true }}
    disable_mlock = {{ .Values.vault.disable_mlock | default true }}
    log_level = "{{ .Values.vault.log_level | default "info" }}"

    storage "file" {
      path = "/vault/data"
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    api_addr = "http://{{ include "vault.fullname" . }}-transit:8200"
    cluster_addr = "http://{{ include "vault.fullname" . }}-transit:8201"
{{- end }}
