apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault.fullname" . }}-vault-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vault.fullname" . }}-vault-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch", "delete", "update", "list"]
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vault.fullname" . }}-vault-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vault.fullname" . }}-vault-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "vault.fullname" . }}-vault-role
  apiGroup: rbac.authorization.k8s.io
