{{- if .Values.main.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}-main-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ include "vault.fullname" . }}-main

  ports:
    - port: 8200
      name: http
    - port: 8201
      name: internal
{{- end }}
