---
name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      # See https://github.com/helm/chart-releaser-action/issues/6

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.5.4
          
      - name: Add Helm Repository
        run: |
          helm repo add jetstack https://charts.jetstack.io

      - name: Update Helm Repositories
        run: helm repo update

      - name: Update Chart Dependencies for redis-operator
        run: helm dependency update charts/redis-operator

      - name: List Changed Charts
        id: list-changed
        run: |
          changed_charts=$(ct list-changed)
          echo "Changed charts: $changed_charts"
          echo "::set-output name=changed_charts::$changed_charts"
          
      - name: Package and Release Charts
        run: |
          for CHART_DIR in $(find charts -maxdepth 1 -type d | tail --lines +2); do
              CHART=$(basename $CHART_DIR)
              echo "Packaging $CHART..."
              helm package $CHART_DIR
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
