apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-proxy-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: kong.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-kong-proxy
                port:
                  number: 8000
