apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-kong-proxy-ingress
  annotations:
    konghq.com/plugins: key-auth,jwt,rate-limit,acl-plugin,request-transformer
spec:
  ingressClassName: nginx
  rules:
    - host: kong.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kong-kong-proxy
                port:
                  number: 8000
