apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: {{ .Values.kong.image }}

          env:
            - name: KONG_DATABASE
              value: "postgres"

            - name: KONG_PG_HOST
              value: {{ .Release.Name }}-postgresql

            - name: KONG_PG_USER
              value: {{ .Values.postgresql.auth.username }}

            - name: KONG_PG_PASSWORD
              value: {{ .Values.postgresql.auth.password }}

            - name: KONG_PG_DATABASE
              value: {{ .Values.postgresql.auth.database }}

            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"

            - name: KONG_ADMIN_GUI_LISTEN
              value: "0.0.0.0:8002"

          ports:
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 8002
