apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kong

spec:
  replicas: {{ .Values.kong.replicaCount }}

  selector:
    matchLabels:
      app: kong

  template:
    metadata:
      labels:
        app: kong

    spec:
      containers:
      - name: kong
        image: {{ .Values.kong.image }}

        env:

        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"

        - name: KONG_ADMIN_GUI_LISTEN
          value: "0.0.0.0:8002"

        {{- if and .Values.kong (default false (index .Values.kong "database" "enabled")) }}
        - name: KONG_DATABASE
          value: "postgres"

        - name: KONG_PG_HOST
          value: "{{ .Release.Name }}-postgresql"

        - name: KONG_PG_USER
          value: {{ default "kong" .Values.postgresql.auth.username | quote }}

        - name: KONG_PG_PASSWORD
          value: {{ default "kongpass" .Values.postgresql.auth.password | quote }}

        - name: KONG_PG_DATABASE
          value: {{ default "kong" .Values.postgresql.auth.database | quote }}

        {{- else }}
        - name: KONG_DATABASE
          value: "off"

        - name: KONG_DECLARATIVE_CONFIG
          value: "/kong/config/kong.yml"
        {{- end }}

        {{- if and .Values.kong (default false (index .Values.kong "plugins" "enabled")) }}
        - name: KONG_PLUGINS
          value: {{ join "," (default (list "bundled") .Values.kong.plugins.list) | quote }}
        {{- end }}

        - name: KONG_STATUS_LISTEN
          value: "0.0.0.0:8100"

        - name: KONG_TRACING_INSTRUMENTATIONS
          value: "all"

        - name: KONG_TRACING_SAMPLING_RATE
          value: "1.0"

        - name: KONG_OPENTELEMETRY_ENDPOINT
          value: {{ default "http://otel-collector:4318" .Values.observability.otel.endpoint | quote }}

        ports:
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
        - containerPort: 8100
