apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kong-proxy
  annotations:
    konghq.com/plugins: key-auth,rate-limit,jwt,prometheus,opentelemetry
spec:
  type: Nodeport
  selector:
    app: kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
