{{- $pg := .Values.postgresql | default dict }}
{{- $auth := $pg.auth | default dict }}

apiVersion: v1
kind: Secret
metadata:
  name: kong-db-secret
type: Opaque

stringData:
  username: "{{ $auth.username | default "kong" }}"
  password: "{{ $auth.password | default "kongpass" }}"
  database: "{{ $auth.database | default "kong" }}"
