{{- $tls := .Values.tls | default dict }}

{{- if $tls.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: kong-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ default "" $tls.crt }}
  tls.key: {{ default "" $tls.key }}

{{- end }}
