{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kong-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | default "" }}
  tls.key: {{ .Values.tls.key | default "" }}
{{- end }}
